### PR TITLE
Install `php*-memcached too

### PR DESCRIPTION
**Pull request by joehoyle**

### CODE REVIEW

**Comment by rmccue** [comment]
Needs checking on all supported versions.

**Comment by BronsonQuick** [comment]
Ahh crap. I missed this PR haha 💃

**Comment by BronsonQuick** [comment]
This works on all versions about from `5.3`

**Comment by joemcgill** [comment]
Got tripped up on this today when trying to set up a new dev box based on the HM-Base repo. Checking out @joehoyle's branch in the extensions directory and running `vagrant provision` fixed the issue for me.

**Comment by mattheu** [comment]
Oh I ran into this one so many times. +1000

**Pull request merged**
